# Generated by Django 3.1.6 on 2021-02-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='grocery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_app.grocery'),
        ),
    ]
