# Generated by Django 3.1.6 on 2021-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0004_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
