# Generated by Django 3.1.6 on 2021-03-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_auto_20210302_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
