# Generated by Django 3.1.6 on 2021-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0006_auto_20210302_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total_amount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
