# Generated by Django 3.1.6 on 2021-03-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0007_auto_20210302_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sub_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
        ),
    ]
