# Generated by Django 3.1.6 on 2021-03-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0008_auto_20210302_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='cc_code',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='cc_expiry',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='cc_number',
        ),
    ]
